wordpress:
  image: tutum/wordpress-stackable
  hostname: inasafe.org
  links: 
   - db
  ports:
   - "2080:80"
  environment:
    DB_NAME: wordpress
    DB_USER: admin
    # Environment variables with only a key are resolved to their 
    # values on the machine Compose is running on.
    # so make sure to set the DB_PASS env var before using this config file
    DB_PASS:
    DB_HOST: db
    DB_PORT: 3306
  volumes_from: 
    # so we can have /backups folder for making backups
    - db
  volumes:
    # This so we can share the app dir as a container storage volume
    - /app
    # so we can persist media
    - wp-content:/app/wp-content

db:
  hostname: db.inasafe.org
  image: tutum/mysql:5.5
  environment:
    # Environment variables with only a key are resolved to their 
    # values on the machine Compose is running on.
    # so make sure to set the MYSQL_PASS env var before using this config file
    MYSQL_PASS:
  volumes:
    - backups:/backups
    # This will not work on OSX/Win - comment out for those oses
    # See https://github.com/tutumcloud/tutum-docker-mariadb/issues/5
    #- db:/var/lib/mysql
